apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-eks-template-github
  title: Provision EKS Cluster - Github
  description: Provision EKS Cluster using Terraform and Github Actions
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform-templates
    - k8s
    - eks
    - terraform
spec:
  owner: veecode/platform
  type: devops
  parameters:
    - title: EKS Configuration
      required:
        - eks_cluster_name
        - capacity_type
        - instance_type
        - node_quantity
        - max_node_quantity
      properties:
        eks_cluster_name:
          title: EKS Cluster name
          type: string
          description: Specifies the EKS Cluster name
        k8s_version:
          title: Kubernetes Version
          type: string
          description: Specifies the EKS Kubernetes Version
          default: "1.23"
          enum:
            - "1.23"
            - "1.22"
            - "1.21"
            - "1.20"
        instance_type:
          title: Node instance type
          type: string
          description: Specifies the EKS Node instance type
          default: t3.small
          enum:
            - t3.small
            - m5.large
            - m5.xlarge
            - t4g.small
            - m6g.large
            - m6g.xlarge
          enumNames:
            - "t3.small (vCPU:2, Mem: 2Gib)"
            - "m5.large (vCPU:2, Mem: 8Gib)"
            - "m5.xlarge (vCPU:4, Mem: 16Gib)"
            - "t4g.small (vCPU:2, Mem: 2Gib)"
            - "m6g.large (vCPU:2, Mem: 8Gib) ARM"
            - "m6g.xlarge (vCPU:4, Mem: 16Gib) ARM"
        capacity_type:
          title: Purchasing option
          type: string
          description: Specifies the Node Group purchasing option
          default: SPOT
          enum:
            - 'ON_DEMAND'
            - 'SPOT'
          enumNames:
            - 'On demand'
            - 'Spot Instance'
            
        node_quantity:
          title: Node Quantity
          type: number
          description: Specifies the Node Group quantity
          default: 1
        max_node_quantity:
          title: Max Node Quantity
          type: number
          description: Specifies the Node Group max quantity
          default: 3
        
    - title: Terraform Configuration
      required:
        - terraform_state_bucket_name
        - terraform_state_bucket_region
      properties:
        terraform_state_bucket_name:
          title: Terraform State Bucket ARN
          type: string
          description: Specifies your Terraform State Bucket

        terraform_state_bucket_region:
          title: Bucket Region
          type: string
          description: Specifies the Terraform State Bucket region
          default: 'us-east-1'
          enum:
            - 'us-east-2'
            - 'us-east-1'
            - 'us-west-1'
            - 'us-west-2'
          enumNames:
            - 'US East (Ohio)'
            - 'US East (N. Virginia)'
            - 'US West (N. California)'
            - 'US West (Oregon)'
          
        infracost:
          title: Enable Infracost Estimate
          type: boolean
          default: false

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Choose a location to create the EKS Cluster Pipeline
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - veecode-platform
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton      
        values:
          eks_cluster_name: ${{ parameters.eks_cluster_name }}
          k8s_version: ${{ parameters.k8s_version }}
          instance_type: ${{ parameters.instance_type }}
          capacity_type: ${{ parameters.capacity_type }}
          node_quantity: ${{ parameters.node_quantity }}
          max_node_quantity: ${{ parameters.max_node_quantity }}
          terraform_state_bucket_name: ${{ parameters.terraform_state_bucket_name }}
          destination: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
          owner: ${{ parameters.owner }}
          terraform_state_bucket_region: ${{ parameters.terraform_state_bucket_region }}
    
    - name: Check Infracost
      if: ${{ parameters.infracost === false }}
      action: fs:delete
      input:
        files: 
          - ./.github/workflows/infracost.yml

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: EKS Cluster ${{ parameters.eks_cluster_name }}
        repoUrl: ${{ parameters.repoUrl }}
    
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
  
  
