
name: Build Publish Spring Boot 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ values.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ values.java_version }}
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          ./gradlew clean build \
          -Dquarkus.kubernetes.ports."http".host-port=4003 \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=registry.hub.docker.com \
          -Dquarkus.container-image.group=veecode \
          -Dquarkus.container-image.username=${{'${{'}} secrets.DOCKER_USERNAME ${{'}}'}} \
          -Dquarkus.container-image.password=${{'${{'}} secrets.DOCKER_PASSWORD ${{'}}'}} \
          -Dquarkus.kubernetes.namespace=vkpr \
          -Dquarkus.kubernetes.ingress.expose=true \
          -Dquarkus.kubernetes.ingress.ingress-class-name=kong \
          -Dquarkus.kubernetes.ingress.host=rest.platform.vee.codes \
          -Dquarkus.kubernetes.ingress.tls."rest.platform.vee.codes-tls".enabled=true \
          -Dquarkus.kubernetes.ingress.tls."rest.platform.vee.codes-tls".hosts=rest.platform.vee.codes \
          -Dquarkus.kubernetes.ingress.annotations."backstage.io/kubernetes-id"=spring-sample-app \
          -Dquarkus.kubernetes.ingress.annotations."cert-manager.io/cluster-issuer"=certmanager-issuer \
          -Dquarkus.kubernetes.ingress.annotations."konghq.com/https-redirect-status-code"=308 \
          -Dquarkus.kubernetes.ingress.annotations."konghq.com/preserve-host"=true \
          -Dquarkus.kubernetes.ingress.annotations."konghq.com/protocols"=https \
          -Dquarkus.kubernetes.ingress.annotations."konghq.com/strip-path"=true \
          -Dquarkus.kubernetes.ingress.annotations."kubernetes.io/tls-acme"=true

      - name: Setting up kubectl client
        uses: azure/setup-kubectl@v3
        with:
           version: 'latest' # default is latest stable
        id: install

      - name: Publish K8S Artifact
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{'${{'}} secrets.API_TOKEN_GITHUB ${{'}}'}}
        with:
          source_file: 'build/kubernetes/kubernetes.yml'
          destination_repo: ${{ values.argoRepoUrl }}
          destination_folder: '/${{values.component_id}}/'
          destination_branch: 'master'
          user_email: 'veecode-bot@vee.codes'
          user_name: 'veecode-bot'
          commit_message: 'A custom message for the commit'

  publish-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yq
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
          yq --version

      - name: "Check if has insomnia workspace"
        id: check_inso_workspace
        uses: andstor/file-existence-action@v1
        with:
          files: ".insomnia/ApiSpec/spc_*.yml"

      - name: Exporting openapi from insomnia workspace
        if: steps.check_inso_workspace.outputs.files_exists == 'true'
        run: |
          npx insomnia-inso export spec "$(cat .insomnia/ApiSpec/spc_*.yml | yq '.fileName')"  --output ./openapi-swagger.yaml

      - name: Build devportal template
        env:
          NAME: ""
          PATH_API: ""
        run: |
          mkdir -p api/
          NAME=`echo $GITHUB_REPOSITORY |awk -F / '{print $2 }'`
          echo $NAME
          touch "api/$NAME.yaml"
          sed --in-place "s|\"|'|g" ./openapi-swagger.yaml
          yq eval ".apiVersion = \"backstage.io/v1alpha1\"" -i "api/$NAME.yaml"
          yq eval ".kind = \"API\" " -i "api/$NAME.yaml"
          yq eval ".metadata.name=strenv(NAME)" -i "api/$NAME.yaml"
          yq eval ".metadata.description= \"$(cat ./openapi-swagger.yaml | yq e '.info.description')\"" -i "api/$NAME.yaml"
          yq eval ".spec.type = \"openapi\"" -i "api/$NAME.yaml"
          yq eval ".spec.lifecycle = \"production\"" -i "api/$NAME.yaml"
          yq eval ".spec.owner = \"consumer\"" -i "api/$NAME.yaml"
          yq eval ".spec.definition = \"$(yq -I4 ./openapi-swagger.yaml)\"" --inplace "api/$NAME.yaml"
          echo "show spec"
          echo "teste"

      - name: Publish to spec house
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{'${{'}} secrets.API_TOKEN_GITHUB ${{'}}'}}
        with:
          destination_branch: ${{ values.branchName }}
          source_file:  'api'
          destination_repo: ${{ values.specPublish }}
          destination_folder: '/'
          user_name: ${{'${{'}} github.actor ${{'}}'}}
          commit_message: 'Pipeline commit'