project:
  name: ${{values.componentId}}
  description: ${{values.description}}
  java:
    package: codes.platform.${{values.artifact}}
  language: java
  framework: springboot
  applicationPort: ${{values.applicationPort}}
