apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    vault.io/secrets-path: devportal
    grafana/tag-selector: "managed by vkpr"
    grafana/alert-label-selector: "alertname=teste-aviso"
spec:
  type: devops
  lifecycle: experimental
  owner: admin
